[[CUDNN_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "2ff87587f59f8a1373db3bf4a483e7eed75dc22f"
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA110.download]]
    sha256 = "0b2a8869f6b325c565dc9a04ca0f99e5d261ed4b70808523c7035d56f1d4d584"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.1.0+0/CUDNN_CUDA110.v8.1.0.x86_64-linux-gnu.tar.gz"
[[CUDNN_CUDA110]]
arch = "powerpc64le"
git-tree-sha1 = "1d3f5c46ca50d7f01bce7eccfd830e20f51fd095"
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA110.download]]
    sha256 = "e0da2e165d78b3082eacc9f13ef5e2ee45ad2a7c35586072ac7cfb87a34f7e29"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.1.0+0/CUDNN_CUDA110.v8.1.0.powerpc64le-linux-gnu.tar.gz"
[[CUDNN_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "3ba658f7d7427dfdf4ae974828aa00daa9a2bae5"
os = "windows"

    [[CUDNN_CUDA110.download]]
    sha256 = "f29e35b9a4139e0a198065bc3e3a2f46d5be678a44221d3065e5889a7adb010d"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.1.0+0/CUDNN_CUDA110.v8.1.0.x86_64-w64-mingw32.tar.gz"
